import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginHorizontal: 4,
    marginVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  imageContainer: {
    width: '100%',
    height: 150,
    backgroundColor: '#f5f5f5',
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  priceText: {
  fontSize: 12,
  marginTop: 2,
  fontWeight:"bold"
},
  bookmarkButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  offerBanner: {
    position: 'absolute',
    top: 12,
    left: 0,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    // maxWidth: '70%',
  },
  offerText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  textCard: {
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
  },
  firmName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 4,
    maxWidth: '65%', 
  },
  area: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 4,
    maxWidth: '65%', 
  },
  cuisineText: {
    fontSize: 12,
    color: '#808080',
    maxWidth: '65%', 
  },
  areamain: {
    alignItems: 'flex-end',
    maxWidth: '35%', 
  },

  reviewBox: {
    backgroundColor: '#048520',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
  },
  reviewText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  promotedBanner: {
  position: 'absolute',
  top: 10,
  left: 10,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 4,
  zIndex: 1,
},
promotedText: {
  color: 'white',
  fontSize: 12,
  fontWeight: 'bold',
},
discountContainer: {
  position: 'absolute',
  bottom: 10,
  left: 10,
  flexDirection: 'row',
  zIndex: 1,
},
offBanner: {
  backgroundColor: '#e23845',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 4,
  marginRight: 5,
},
offText: {
  color: 'white',
  fontSize: 12,
  fontWeight: 'bold',
},
proExtraBanner: {
  backgroundColor: '#4CAF50',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 4,
},
proExtraText: {
  color: 'white',
  fontSize: 12,
  fontWeight: 'bold',
},
timeContainer: {
  position: 'absolute',
  bottom: 10,
  right: 10,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 4,
  zIndex: 1,
},
timeText: {
  color: 'white',
  fontSize: 12,
  fontWeight: 'bold',
},
});