import { Dimensions,StyleSheet } from "react-native";

const{width} = Dimensions.get("window")

const NotifcationStyles = StyleSheet.create({
  background:{
    backgroundColor:"white",
    display:"flex",
    flexDirection:"column",
    flex:1
  },
  headingContainer:{
    display:"flex",
    flexDirection:"row",
    marginTop:0,
    marginLeft:0,
    padding:10
  },
  HeadingText:{
    fontSize:20,
    color:"#000000",
    fontWeight:"600",
    marginLeft:10
  },
  NotficationContainer:{
    display:"flex",
    flexDirection:"column",
    padding:10,
    borderBottomWidth:7,
    borderBottomColor:"#f0f0f1",
    marginTop:25
  }, 
  NotficationContainer2:{
    display:"flex",
    flexDirection:"column",
    padding:10,
    borderBottomWidth:7,
    borderBottomColor:"#f0f0f1",
    marginTop:10
  },
  PushnotificationContainer:{
    display:"flex",
    flexDirection:"row",
    padding:4,
    justifyContent:"space-between",
    marginRight:10
  },
  togglebutton:{
    elevation:5,
    paddingBottom:1,
    paddingTop:0,
    marginTop:0
  },
  PushnotificationContainer2:{
    display:"flex",
    flexDirection:"row",
    padding:10,
    borderBottomWidth:1,
    borderBottomColor:"#f0f0f1",
    paddingBottom:15,
    justifyContent:"space-between",
    marginRight:10
  },
  PushnotificationContainer3:{
    display:"flex",
    flexDirection:"row",
    padding:10,
    paddingBottom:15,
    paddingTop:20,
    justifyContent:"space-between",
    marginRight:10
  
  },
  NotificationText:{
    fontSize:18,
    color:"#000000",
    fontWeight:"500",
    marginLeft:6
  },
  NotificationText2:{
    fontSize:14,
    color:"#000000",
    fontWeight:"500",
    marginLeft:8,
    marginTop:10,
    marginBottom:10
  },
  notificationTextcontainer:{
    display:"flex",
    flexDirection:"row"
  },
  NotificationText3:{
    fontSize:16,
    color:"#000000",
    fontWeight:"500",
    marginLeft:8,
    marginTop:10,
    marginBottom:10
  },
  SavechangesButton:{
    display:"flex",
    flexDirection:"row",
    marginLeft:10,
    justifyContent:"center",
    marginRight:10,
    borderRadius:7,
    backgroundColor:"#e6e9f0",
    position:"absolute",
    bottom:30,
    left:0,
    right:0,
    padding:13
  },
  savechangesText:{
    fontSize:16,
    fontWeight:"500",
    color:"#aeb2be"
  },
  SavechangesButtonActive:{
    display:"flex",
    flexDirection:"row",
    marginLeft:10,
    justifyContent:"center",
    marginRight:10,
    borderRadius:7,
    backgroundColor:"#ea4c5f",
    position:"absolute",
    bottom:30,
    left:0,
    right:0,
    padding:13
  },
  savechangesTextAtive:{
    fontSize:16,
    fontWeight:"500",
    color:"white"
  }

});
export default NotifcationStyles;
