// TakeAwayCartStyles.jsx
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#f8f9fa' 
  },
  scroll: { 
    padding: 16, 
    paddingBottom: 100 
  },
  
  // Cart Summary Styles
  cartSummary: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 15,
    marginBottom:20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
     fontFamily: 'outfit-medium',
    
    fontSize: 20,
    fontWeight: '700',
    textAlign:'center',
    marginBottom: 15,
    color: '#2d3748',
  },
  emptyCartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyCartImage: {
    width: 180,
    height: 180,
    resizeMode: 'contain',
    marginBottom: 20,
    opacity: 0.8,
  },
  emptyCartText: {
     fontFamily: 'outfit',
    fontSize: 16,
    color: '#e22828ff',
    marginTop: 10,
  },
  itemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // paddingVertical: 10,
    borderTopColor:'#dfe6eeff',
    borderTopWidth:1,
    // borderBottomWidth: 1,
    // borderBottomColor: '#edf2f7',
  },
  itemInfo: {
    flex: 1,
    marginRight: 10,
  },
  itemText: {
     fontFamily: 'outfit-bold',
    fontSize: 18,
    color: '#2d3748',
     marginVertical: 5,
    fontWeight: '500',
  },
  itemPrice: {
     fontFamily: 'outfit-bold',
    fontSize: 16,
    color: '#1f1f20ff',
    marginBottom:5,
  },
    itemPrices: {
       fontFamily: 'outfit-medium',
    fontSize: 14,
    color: '#6d6a6aff',
  },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor:'#000',
    gap: 5,
  },
  // controlButton: {
  //   width: 36,
  //   height: 36,
  //   borderRadius: 18,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: '#edf2f7',
  // },
  controlButtonText: {
     fontFamily: 'outfit',
    fontSize: 30,
    color: '#4a5568',
  },
  quantityText: {
     fontFamily: 'outfit-bold',
    fontSize: 24,
    color: '#2d3748',
    minWidth: 24,
    textAlign: 'center',
    fontWeight: '500',
  },
  deleteButton: {
    marginLeft: 8,
    padding: 6,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    gap: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 3,
  },
  phone:{
   flexDirection: 'row',
       justifyContent:'space-between'
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
  },
  info: { 
    flex: 1 
  },
  label: { 
    color: '#4a5568', 
    fontSize: 14,
      fontFamily: 'outfit',
    marginBottom: 4,
  },
  bold: { 
    fontWeight: '600' 
  },
  link: {
    color: '#4299e1',
    fontSize: 13,
    textDecorationLine: 'underline',
    marginTop: 2,
  },
  address: { 
    color: '#718096', 
    fontSize: 13 ,
      fontFamily: 'outfit',
  },
  striked: { 
    textDecorationLine: 'line-through', 
    color: '#a0aec0', 
    fontSize: 14 ,
      fontFamily: 'outfit',
  },
  boldPrice: { 
      fontFamily: 'outfit',
    color: '#2d3748', 
    fontWeight: '700', 
    fontSize: 16 
  },
  billRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  badge: {
    backgroundColor: '#ebf8ff',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginLeft: 8,
  },
  badgeText: { 
    color: '#3182ce', 
    fontSize: 12, 
    fontWeight: '600' 
  },
  subLabel: { 
    color: '#a0aec0', 
    fontSize: 12, 
    marginTop: 4 
  },

  // Cancellation policy styles
  cancelTitle: {
    fontSize: 16,
      fontFamily: 'outfit-bold',
    fontWeight: '600',
    marginTop: 10,
    color: '#4a5568',
    letterSpacing: 0.5,
  },
  cancelText: {
      fontFamily: 'outfit-medium',
    fontSize: 14,
    color: '#718096',
    marginVertical: 6,
    lineHeight: 20,
  },

  // Footer styles
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    // paddingHorizontal:10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 5,
  },
  paymentMethod: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  payUsing: {
      fontFamily: 'outfit',
    fontSize: 12,
    color: '#a0aec0',
    letterSpacing: 0.5,
  },
  payMethod: {
      fontFamily: 'outfit',
    fontSize: 14,
    fontWeight: '600',
    color: '#2d3748',
    marginTop: 2,
  },
  placeOrderBtn: {
    backgroundColor: '#ffffffff',
    borderRadius: 10,
    marginLeft: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
    // shadowColor: '#e53e3e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  totalText: {
      fontFamily: 'outfit',
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  placeText: {
      fontFamily: 'outfit',
    fontSize: 16,
    color: '#fff',
    marginTop: 2,
  },
  disabledButton: {
    opacity: 0.6,
  },

  // Picker styles
  // pickerContainer: {
  //   borderWidth: 1,
  //   borderColor: '#e2e8f0',
  //   borderRadius: 8,
  //   backgroundColor: 'white',
  //   marginBottom: 12,
  //   overflow: 'hidden',
  // },
  // picker: {
  //   width:100,
  //   height: 50,
  //   color: '#2d3748',
  //   paddingLeft:10,
  // },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickup: {
    flex: 1,
    backgroundColor: 'white',
    marginTop: 10,
    // padding: 16,
    borderRadius: 12,
  },
  modalContent: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  modalTitle: {
      fontFamily: 'outfit-bold',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    color: '#2d3748',
  },
  modalSub: {
      fontFamily: 'outfit',
    fontSize: 14,
    color: '#718096',
    marginBottom: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 14,
    marginBottom: 16,
    fontSize: 16,
    fontFamily: 'outfit-medium',
    backgroundColor: '#fff',
  },
  submitBtn: {
    backgroundColor: '#e53e3e',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
      fontFamily: 'outfit',
  },

  // Restaurant header styles
  restaurantHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    // padding: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 20,
  },
  restaurantImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 12,
  },
  restaurantHeaderText: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  restaurantName: {
      fontFamily: 'outfit-bold',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    color: '#2d3748',
  },
  restaurantAddress: {
      fontFamily: 'outfit-medium',
    fontSize: 14,
    color: '#718096',
    lineHeight: 18,
  },

  // Bill Summary Modal Styles
  billSummaryTitle: {
      fontFamily: 'outfit-bold',
    fontSize: 18,
    marginTop: 8,
    marginBottom: 20,
    color: '#2d3748',
    textAlign: 'center',
  },
  billRowItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#edf2f7',
  },
  billLabel: {
    color: '#4a5568',
    fontSize: 15,
      fontFamily: 'outfit',
  },
  billValue: {
    color: '#2d3748',
    fontSize: 15,
      fontFamily: 'outfit',
    fontWeight: '500',
  },
  savingsContainer: {
    marginTop: 20,
    padding: 14,
    backgroundColor: '#ebf8ff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bee3f8',
  },
  savingsText: {
    color: '#3182ce',
    fontSize: 15,
      fontFamily: 'outfit',
    fontWeight: '600',
    textAlign: 'center',
  },
  closeButton: {
    marginTop: 24,
    backgroundColor: '#e53e3e',
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
      fontFamily: 'outfit-bold',
  },

  // Promotion and Coupon Styles
  promotionContainer: {
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom:20,
    borderColor: '#edf2f7',
      shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
      fontFamily: 'outfit-bold',
    fontSize: 18,
    marginBottom: 10,
    color: '#2d3748',
  },
  addPromoButton: {
    borderWidth: 1,
    borderColor: '#4299e1',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#ebf8ff',
  },
  addPromoButtonText: {
    color: '#3182ce',
    fontSize: 16,
      fontFamily: 'outfit-bold',
    fontWeight: '600',
  },
  appliedPromoContainer: {
    backgroundColor: '#ebf8ff',
    borderColor: '#90cdf4',
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appliedPromoText: {
    color: '#3182ce',
    fontSize: 15,
      fontFamily: 'outfit',
    fontWeight: '600',
    flex: 1,
    marginLeft: 10,
  },
  emoji: {
    fontSize: 24,
      fontFamily: 'outfit',
  },
  removePromoButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#e53e3e',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  removePromoButtonText: {
    color: '#fff',
    fontSize: 18,
      fontFamily: 'outfit',
    fontWeight: 'bold',
  },
  viewAllCouponsButton: {
    marginTop: 12,
    alignSelf: 'flex-end',
  },
  viewAllCouponsText: {
    color: '#3182ce',
    fontSize: 14,
      fontFamily: 'outfit',
    fontWeight: '500',
    textDecorationLine: 'underline',
  },

  // Promo Card Styles
  promoCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  promoName: {
      fontFamily: 'outfit-bold',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 6,
    color: '#2d3748',
  },
  promoCode: {
      fontFamily: 'outfit-medium',
    fontSize: 14,
    color: '#718096',
    marginBottom: 6,
    fontFamily: 'monospace',
  },
  promoDiscount: {
      fontFamily: 'outfit-bold',
    fontSize: 15,
    fontWeight: '500',
    color: '#38a169',
    marginBottom: 8,
  },
  promoDate: {
      fontFamily: 'outfit',
    fontSize: 14,
    color: '#a0aec0',
  },
  promoApplyButton: {
    backgroundColor: '#de2222ff',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignSelf: 'flex-end',
  },
  promoApplyButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  taxDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#edf2f7',
  },
  addressInputContainer: {
    position: 'relative',
    // marginBottom: 15,
  },
  clearAddressText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  paymentMethodContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    flexDirection: 'row',
    // marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  paymentOptions: {
    // flexDirection: 'row',
    justifyContent: 'space-around',
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    minWidth: 120,
    justifyContent: 'center',
    gap: 8,
  },
  selectedPaymentOption: {
    backgroundColor: '#4299e1',
    borderColor: '#4299e1',
  },
  paymentOptionText: {
    fontSize: 14,
      fontFamily: 'outfit-bold',
    fontWeight: '600',
    color: '#4a5568',
  },
  selectedPaymentText: {
    color: '#fff',
  },

  // Checkout Button Styles
  checkoutButton: {
    backgroundColor: '#e53e3e',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical:15,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
     shadowColor: '#5c5454ff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
    // marginTop: 16,
  },
  checkoutButtonDisabled: {
    backgroundColor: '#ffffffff',
    opacity: 0.7,
  },
  checkoutButtonDisabledtext:{
color:'#000'
  },
  checkoutButtonText: {
    color: '#ffffffff',
    fontSize: 16,
      fontFamily: 'outfit-bold',
    fontWeight: '600',
  },
  phone: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginBottom: 16,
},
pickerContainer: {
  width: '28%', // Takes 20% of the width
  borderWidth: 1,
  borderColor: '#e2e8f0',
  borderRadius: 8,
  backgroundColor: '#fff',
  marginRight: 10,
},
picker: {
  height: 50,
},
phoneinput: {
  borderWidth: 1,
  borderColor: '#e2e8f0',
  borderRadius: 8,
  padding: 10,
    height: 50,
  // marginBottom: 16,
  fontSize: 15,
    fontFamily: 'outfit-medium',
  width: '70%', 
  backgroundColor: '#fff',
},
  // Bill Modal Styles
  modalScroll: {
    maxHeight: 400,
  },
  billSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#edf2f7',
  },
  billSectionTitle: {
    fontSize: 15,
    fontFamily: 'outfit-bold',
    color: '#4a5568',
  },
  billAmount: {
    fontFamily: 'outfit-medium',
    fontSize: 15,
    color: '#2d3748',
    fontWeight: '500',
  },
  taxDetails: {
    marginLeft: 16,
    marginTop: 8,
  },
  taxRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  taxName: {
    fontFamily: 'outfit-medium',
    fontSize: 14,
    color: '#718096',
  },
  taxAmount: {
    fontFamily: 'outfit-medium',
    fontSize: 14,
    color: '#718096',
    fontWeight: '500',
  },
  totalSection: {
    borderTopWidth: 2,
    borderTopColor: '#e2e8f0',
    marginTop: 8,
    paddingTop: 16,
  },
  totalText: {
      fontFamily: 'outfit-bold',
    fontSize: 16,
    color: '#2d3748',
  },
  totalAmount: {
      fontFamily: 'outfit-bold',
    fontSize: 18,
    color: '#e53e3e',
  },
});