import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    // marginTop: 10,
    padding: 10,
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  activeFilterButtonText: {
    color: '#08a742',
  },
  deliveryTimeProgress: {
    marginBottom: 16,
  },
  // deliveryTimeLabel: {
  //   fontSize: 16,
  //   fontWeight: '600',
  //   marginBottom: 8,
  //   color: '#333',
  // },
  filterIconButton: {
    paddingHorizontal: 16,
  },
  secondaryTabContainer: {
    flexDirection: 'row',
    backgroundColor: 'white',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  orderStatus: {
    fontSize: 14,
    fontWeight: '500',
    marginTop: 2,
    textTransform: 'capitalize',
  },
  secondaryTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeSecondaryTab: {
    borderBottomColor: '#08a742',
  },
  secondaryTabText: {
    fontSize: 15,
    color: '#666',
  },
  activeSecondaryTabText: {
    color: '#08a742',
    fontWeight: '500',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: '#666',
  },
  errorContainer: {
    padding: 20,
    backgroundColor: '#FFEBEE',
    margin: 20,
    borderRadius: 8,
    alignItems: 'center',
  },
  errorText: {
    color: '#C62828',
    fontWeight: 'bold',
    marginBottom: 5,
  },
  errorSubtext: {
    color: '#666',
    fontSize: 12,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 8,
    fontWeight: 'bold',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999',
  },
  bookingsList: {
    padding: 10,
    // paddingBottom: 80,
  },
  orderCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 10,
    padding: 3,
    paddingTop: 13,
    paddingLeft: 13,
    paddingRight: 13,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  selectedOrderCard: {
    borderWidth: 2,
    borderColor: '#08a742',
  },
  // cardImageContainer: {
  //    flexDirection: 'row',
  //   justifyContent: 'space-between',
  //   alignItems: 'flex-start',
  //   marginBottom: 12,
  // },
  // cardImage: {
  //   width: 100,
  //   height: 80,
  //   borderRadius: 8,
  //   marginRight: 12,
  // },
  restaurantHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  restaurantInfo: {
    flexDirection: 'row',
    flex: 1,
  },
  restaurantImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    marginRight: 12,
  },
  restaurantDetails: {
    padding: 10,
    // width:200,
    flex: 1,
  },
  restaurantName: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    color: '#333',
  },
  orderDate: {
    marginBottom: 10,
    fontSize: 14,
    color: '#666',
  },
  statusBadge: {
    // position: 'absolute',
    // top: 10,
    // left: 10,
    // paddingHorizontal: 20,
    // paddingVertical: 8,
    // borderRadius: 10,
    // borderWidth: 1,
  },
  deliveredBadge: {
    backgroundColor: '#E8F5E9',
    borderColor: '#C8E6C9',
  },
  pendingBadge: {
    backgroundColor: '#FFF3E0',
    borderColor: '#FFE0B2',
  },
  activeBadge: {
    backgroundColor: '#E3F2FD',
    borderColor: '#BBDEFB',
  },
  cancelledBadge: {
    color: '#ec0e2fff',
    borderColor: '#FFCDD2',
  },
  defaultBadge: {
    backgroundColor: '#F5F5F5',
    borderColor: '#E0E0E0',
  },
  statusBadgeText: {
    fontSize: 15,
    fontWeight: '500',
  },
  orderIdBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'white',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  orderIdText: {
    fontSize: 12,
    color: '#666',
  },
  cardContent: {
    padding: 10,
  },
  tiffinName: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#333',
  },
  mealType: {
    fontSize: 14,
    color: '#666',
    marginBottom: 12,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 12,
  },
  priceText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  viewDetailsButton: {
    backgroundColor: '#08a742',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  viewDetailsButtonText: {
    color: 'white',
    fontWeight: '600',
  },
  loadingMoreContainer: {
    padding: 16,
    alignItems: 'center',
  },
  loadingMoreText: {
    marginTop: 8,
    color: '#666',
  },
  noMoreOrdersText: {
    textAlign: 'center',
    padding: 16,
    color: '#999',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(27, 27, 27, 0.16)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    width: '90%',
    maxHeight: '90%',
    backgroundColor: '#ffffffff',
    padding: 15,
  },
  cancelModalContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    width: '90%',
    maxHeight: '80%',
    padding: 16,
  },
  modalHeader: {
    // flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  closeButton: {
    padding: 4,
  },
  modalContent: {
    flexGrow: 1,
  },
  specialInstructionsContainer: {
    backgroundColor: '#f9fafb',
    padding: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginBottom: 10,
    width: '100%'
  },
  instructionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4
  },
  instructionTitle: {
    fontWeight: '600',
    fontSize: 15,
  },
  instructionText: {
    fontStyle: 'italic',
    marginLeft: 30,
    color: '#4b5563'
  },
  icon: {
    marginRight: 8
  },
  section: {
    backgroundColor: '#fff',
    // borderRadius: 12,
    marginBottom: 15,
    // padding: 15,
    // elevation: 2,
    // shadowColor: '#000',
    // shadowOffset: { width: 0, height: 2 },
    borderBottomWidth:1,
    borderBottomColor: '#EBDDD9',
    // shadowOpacity: 0.1,
    // shadowRadius: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: '#333',
  },
  progressSection: {
    backgroundColor: '#FFE5E8',
    padding: 12,
    marginBottom: 15,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  progressBarBackground: {
    height: 8,
    backgroundColor: '#FFB2BB',
    borderRadius: 4,
    marginBottom: 8,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#FF002E',
    borderRadius: 4,
  },
  progressInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  progressText: {
    fontSize: 12,
    color: '#666',
  },
  progressPercent: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FF002E',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginHorizontal: 10,
  },
  infoText: {
    marginHorizontal: 10,
    marginVertical: 5,
    fontSize: 14,
    color: '#575656ff',
  },
  orderItem: {
    // flexDirection: 'column',
    backgroundColor: '#ffffffff',
    // padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  itemName: {
    fontWeight: '600',
    marginBottom: 4,
  },
  itemDetails: {
 marginBottom:8,
  },
  // itemDetail: {
  //   fontSize: 14,
  //   color: '#666',
  //   marginRight: 12,
  //   marginBottom: 4,
  // },
  paymentTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  paymentDetails: {
    marginBottom: 8,
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  paymentLabel: {
    fontSize: 14,
    color: '#666',
  },
  paymentValue: {
    fontSize: 14,
    color: '#333',
  },
  discountText: {
    color: '#E53935',
  },
  totalPaymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  totalPaymentLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  totalPaymentValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#08a742',
  },
  orderItems: {
    marginBottom: 12,
  },
  orderItemt: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  vegIcon: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderColor: '#0f8a65',
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  vegIconInner: {
    width: 8,
    height: 8,
    backgroundColor: '#0f8a65',
    borderRadius: 4,
  },
  nonVegIcon: {
    borderColor: '#e23744',
  },
  nonVegIconInner: {
    backgroundColor: '#e23744',
  },
  itemText: {
    fontSize: 14,
    color: '#333',
    flex: 1,
  },
  timeline: {
    marginLeft: 15,
    borderLeftWidth: 2,
    borderLeftColor: '#BDBDBD',
    paddingLeft: 19,
  },
  timelineItem: {
    marginBottom: 16,
    position: 'relative',
  },
  timelineDot: {
    position: 'absolute',
    left: -30,
    top: 0,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#08a742',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timelineContent: {
    paddingBottom: 8,
  },
  timelineStatus: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 4,
  },
  latestBadge: {
    backgroundColor: '#E3F2FD',
    color: '#1976D2',
    fontSize: 14,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  timelineDate: {
    fontSize: 14,
    color: '#757575',
  },
  cancelButtonContainer: {
    // marginTop: 20,
    // borderTopWidth: 1,
    // borderTopColor: '#eee',
    paddingTop: 16,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#E53935',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  cancelButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
  cancelModalText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 16,
  },
  cancelReasonInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    minHeight: 120,
    marginBottom: 16,
    textAlignVertical: 'top',
  },
  cancelModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  cancelModalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelModalButtonSecondary: {
    backgroundColor: '#f5f5f5',
    marginRight: 8,
  },
  cancelModalButtonPrimary: {
    backgroundColor: '#E53935',
    marginLeft: 8,
  },
  cancelModalButtonSecondaryText: {
    color: '#666',
    fontWeight: '600',
  },
  cancelModalButtonPrimaryText: {
    color: 'white',
    fontWeight: '600',
  },
  errorMessage: {
    color: '#C62828',
    marginBottom: 16,
    textAlign: 'center',
  },
  successMessage: {
    color: '#08a742',
    marginBottom: 16,
    textAlign: 'center',
  },
  deliveryTimeProgress: {
    marginBottom: 16,
  },
  deliveryTimeLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    color: '#333',
  },
  timelineSlotContainer: {
    marginBottom: 16,
  },
  timelineSlotTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: '#333',
    paddingLeft: 35, // Align with timeline items
  },
  // orderItem: {
  //   marginBottom: 16,
  //   paddingBottom: 16,
  //   borderBottomWidth: 1,
  //   borderBottomColor: '#f5f5f5',
  // },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#222',
    flex: 1,
    marginRight: 10,
  },
  itemPrice: {
    paddingRight: 50,
    fontSize: 15,
    fontWeight: '600',
    color: '#2e7d32', // Green color for price
  },
  itemDetails: {
    marginLeft: 8,
  },
  detailRow: {
    flexDirection: 'row',
    // alignItems:'center',
    justifyContent:'space-between',
    marginBottom: 6,
  },
  detailLabel: {
    fontSize: 14,
    color: '#666',
    width: 100,
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 14,
    color: '#020202ff',
    // flex: 1,
    textAlign:'center'
  },
  descriptionText: {
    fontStyle: 'bold',
  },
  deliveryTimeContainer: {
    flexDirection: 'row',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#EBDDD9',
  },
    deliveryTimeContainert: {
    // flexDirection: 'row',
    // marginTop: 12,
    // paddingTop: 12,
    // borderTopWidth: 1,
    marginLeft:10,
  },
  deliveryTimeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#656565ff',
    marginBottom: 4,
  },
  deliveryTimeText: {
    fontSize: 14,
    color: '#090909ff',
    marginLeft: 8,
    marginBottom: 2,
  },
});