import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    color: '#666',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
    reviewBoxTopContainer: {
    backgroundColor: 'green',
    padding: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10
  },
  reviewBoxUpperContainer: {
    flexDirection: 'row',
  },
  reviewBoxBottomContainer: {
    backgroundColor: 'white',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10
  },
  reviewText: {
    fontFamily: 'outfit',
    color: 'white',
    fontSize: 18,
    marginRight: 7,
  },
  reviewCount: {
    fontFamily: 'outfit',
    fontSize: 14,
    textAlign: 'center'
  },
    reviewBox: {
      bottom:90,
      width:80,
    borderRadius: 10,
    left:300,
    borderWidth: 1,
    borderColor: '#ccc'
  },
  errorText: {
    fontSize: 18,
    color: '#FF4500',
    marginVertical: 16,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: '#FF4500',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    height: 56,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
  },
  contentContainer: {
    bottom:90,
    padding: 16,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  rating: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    marginRight: 8,
  },
  ratingText: {
    marginLeft: 4,
    fontWeight: 'bold',
  },
  description: {
    fontSize: 14,
    color: '#444',
    marginBottom: 14,
    lineHeight: 24,
  },
  descriptions: {
    fontSize: 16,
    // fontWeight: 'bold',
    color: '#444',
    marginBottom: 16,
    lineHeight: 24,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoText: {
    marginLeft: 8,
    color: '#666',
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  tag: {
    marginRight: 8,
    marginBottom: 8,
  },
  bottomBar: {
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  checkoutButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    opacity: 1,
  },
  checkoutButtonDisabled: {
    opacity: 0.5,
  },
  checkoutButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  checkoutButtonPrice: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  TermsContainer: {
    padding: 20,
    backgroundColor: '#f9f9f9',
    // marginBottom: 10,
  },
  addOnModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  addOnModalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: '80%',
  },
  addOnModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  addOnItemName: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
  },
  addOnItemPrice: {
    fontSize: 16,
    color: '#4CAF50',
    textAlign: 'center',
    marginBottom: 20,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  quantityButton: {
    padding: 10,
    borderRadius: 5,
    backgroundColor: '#f8f8f8',
  },
  quantityText: {
    marginHorizontal: 20,
    fontSize: 18,
    fontWeight: 'bold',
  },
  addOnModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  cancelButton: {
    borderColor: '#FF4B3A',
    flex: 1,
    marginRight: 10,
  },
  submitButton: {
    backgroundColor: '#4CAF50',
    flex: 1,
    marginLeft: 10,
  },
  menuImageContainer: {
    marginVertical: 10,
    padding: 16,
    // backgroundColor: '#f9f9f9',
    borderRadius: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#333',
  },
  // menuImage: {
  //   width: '100%',
  //   height: 200,
  //   borderRadius: 8,
  // },
  galleryContainer: {
 height:height*0.2,
    width: width*0.4,
    borderRadius:20,
  },
  customizeButton: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 16,
  },
  customizeButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  cartButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#4CAF50',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  cartButtonText: {
    color: 'white',
    fontWeight: 'bold',
    marginLeft: 8,
    fontSize: 16,
  },
  cartBadge: {
    backgroundColor: 'red',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  cartBadgeText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  container: {
    flex: 2,
    // backgroundColor: '#f8f8f8',
  },
  filterContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  filterButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterButtonSelected: {
    backgroundColor: '#f0f0f0',
  },
  filterButtonText: {
    color: '#666',
    fontWeight: '500',
    marginLeft: 4,
  },
  vegFilterButton: {
    backgroundColor: '#4CAF50',
  },
  vegFilterButtonSelected: {
    backgroundColor: '#4CAF50',
  },
  vegFilterText: {
    color: '#fff',
  },
  nonVegFilterButton: {
    backgroundColor: '#FF4B3A',
  },
  nonVegFilterButtonSelected: {
    backgroundColor: '#FF4B3A',
  },
  nonVegFilterText: {
    color: '#fff',
  },
  menuCategories: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  categoriesContainer: {
    paddingHorizontal: 16,
  },
  categoryButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
  },
  categoryButtonSelected: {
    backgroundColor: '#FF4B3A',
  },
  categoryButtonText: {
    color: '#666',
    fontWeight: '500',
  },
  categoryButtonTextSelected: {
    color: '#fff',
  },
  menuList: {
    padding: 16,
  },
  menuItem: {
    marginBottom: 16,
    // backgroundColor: '#fff',
    // elevation: 2,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  menuItemImageContainer: {
    width: 150,
    height:160,
  },
  menuItemImage: {
    width: '100%',
    height: 130,
    resizeMode: 'cover',
    borderRadius: 12,
  },
  menuItemContent: {
    flex: 1,
    paddingHorizontal:20,
    paddingVertical: 10,
    justifyContent: 'space-between',
  },
  imageBottomContainer: {
    position: 'absolute',
    bottom: -10,
    left: 0,
    right: 0,
    padding: 10,
    alignItems: 'center',
  },
  menuItemHeader: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuItemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  menuItemDescription: {
    fontSize: 13,
    color: '#666',
    marginBottom: 8,
    lineHeight: 18,
    flexShrink: 1,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 12,
    color: '#666',
    marginLeft: 4,
  },
  menuItemPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF4B3A',
    marginBottom: 8,
  },
  customizableText: {
    fontSize: 12,
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  menuItemActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButtons: {
    flexDirection: 'row',
  },
  iconButton: {
    marginRight: 12,
  },
  addButton: {
    bottom:15,
    left:10,
    // paddingBottom:10,
    borderRadius: 10,
    backgroundColor: '#FF4B3f',
    width:130,
    paddingHorizontal: 50,
    paddingVertical:4,
    height: 30,
  },
  addButtonc: {
    bottom:15,
    // left:10,
    // paddingBottom:10,
    borderRadius: 10,
    // backgroundColor: '#FF4B3f',
    // width:130,
    paddingHorizontal: 40,
    paddingVertical:5,
    height: 30,
  },
  addButtonActive: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minWidth: 80,
  },
  addButtonLabel: {
    // paddingBottom:10,
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  addButtonLabelc: {
    paddingBottom:10,
    // color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  quantityText: {
    // bottom:10,
    color: '#000000',
    marginRight: 8,
    fontSize: 18,
  },
  vegIndicator: {
    marginRight: 6,
  },
  bestsellerBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 4,
  },
  bestsellerText: {
    color: '#fff',
    fontSize: 10,
    marginLeft: 2,
  },
  vegBadge: {
    position: 'absolute',
    left: 4,
    top: 3,
    backgroundColor: '#fff',
    padding: 2,
    borderRadius: 8,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    marginTop: 10,
    color: '#666',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyStateText: {
    marginTop: 10,
    color: '#666',
  },
  // Add these new styles to your existing StyleSheet
bottomCheckoutBar: {
  position: 'absolute',
  bottom: 0,
  left: 0,
  right: 0,
  backgroundColor: '#fff',
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingVertical: 12,
  paddingHorizontal: 16,
  borderTopWidth: 1,
  borderTopColor: '#eee',
  elevation: 8,
},
checkoutButton: {
  flex: 1,
  borderRadius: 8,
  backgroundColor: '#FF4B3A',
  paddingVertical: 12,
  marginLeft: 8,
},
checkoutButtonText: {
  color: '#fff',
  fontWeight: 'bold',
  fontSize: 16,
  textAlign: 'center',
},
quantityControls: {
  bottom:10,

  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  backgroundColor: '#f0f0f0',
  borderRadius: 20,
  paddingHorizontal: 8,
  paddingVertical: 4,
},
quantityButton: {
  // padding: 8,
},
customizeButton: {
  paddingHorizontal: 40,
  paddingVertical:3,
  // borderColor: '#FF4B3A',
  // borderWidth: 1,
  // borderRadius: 8,
  // paddingVertical: 10,
  // marginRight: 8,
},
customizeButtonLabel: {
  color: '#FF4B3A',
  fontSize: 14,
},
checkoutTotal: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#333',
  marginRight: 8,
},
checkoutQuantity: {
  fontSize: 14,
  color: '#666',
},
customizeContainer: {
  marginTop: 20,
  padding: 16,
  backgroundColor: '#f9f9f9',
  borderRadius: 8,
  borderWidth: 1,
  borderColor: '#e0e0e0',
},
customizeDescription: {
  fontSize: 14,
  color: '#666',
  marginBottom: 16,
  lineHeight: 20,
},
customizeButton: {
  backgroundColor: '#4CAF50',
  borderRadius: 8,
  paddingVertical: 8,
},
customizeButtonText: {
  color: 'white',
  fontWeight: 'bold',
},
  proceedToCartButton: {
    backgroundColor: '#e23845',
    padding: 15,
    borderRadius: 5,
    margin: 10,
    alignItems: 'center',
  },
  controlButton: {
    fontFamily: 'outfit-bold',
    fontSize: 24,
    color: '#e23845',
    paddingHorizontal: 10,
  },
  proceedToCartText: {
    fontFamily: 'outfit-bold',
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
  },
});

export default styles;
